name: dockerhub
on:
  push:
    branches:
      - "master"
    # paths:
    #   - 'src/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for Docker Hub
        run: |
          docker build -t marriprasanth/javaapp:v1 -f Dockerfile.dockerhub .
          docker tag marriprasanth/javaapp:v1 dkutti/javaapp:v1
      - name: Push Docker image to Docker Hub
        run: |
          docker push dkutti/javaapp:v1