name: dockerhub
on:
  push:
    branches:
      - "master"
    paths:
      - 'Dockerfile.dockerhub'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Docker image for Docker Hub
        run: |
          docker build -t marriprasanth/time_no_run:v1 -f Dockerfile.dockerhub .
          docker tag marriprasanth/time_no_run:v1 dkutti/time_no_run:v1
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Push Docker image to Docker Hub
        run: docker push dkutti/time_no_run:v1