# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
on: [push]

jobs:
  build:

    runs-on: ${{matrix.os}}
    if: contains(github.event.head_commit.message, '[python-app]')
    steps: 
    - name: Run this job if it is python-app.yml 
      run: echo "Running python-app.yml"
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.12"]
        # Excluding a version 3.10 and OS
        exclude:
          - os: windows-latest
            python-version: "3.10"
          # - os: windows-latest
          #   python-version: "3.12"
        

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependency
        run: python3 -m pip install --upgrade pip
